id: P003312
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 10:54:23.160647
source_metadata:
  id: bdr:W1KG1790
  title: ཡི་གེའི་འཇུག་སྒོ
  author: ''
  volumes:
    8a5ea115fe18412babf62b51efc16084:
      image_group_id: I1KG1806
      title: ''
      volume_number: 1
      total_pages: 53
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
