id: I15541753
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T03:49:09+00:00'
last_modified: '2022-06-07T19:00:18.515622+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1790
  title: ཡི་གེའི་འཇུག་སྒོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EAA8:
      image_group_id: I1KG1806
      title: ''
      total_pages: 53
      order: 1
      base_file: EAA8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
